apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qn9xisxx1-python
  janus-idp.io/tekton: qn9xisxx1-python
  backstage.io/kubernetes-id: qn9xisxx1-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qn9xisxx1-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
